In spite module org.netbeans.core.multiview is part of platform, it is enabled only if other module depends on it. If not enabled, we just catch NoClassDefFoundError without any other harm.