#134455: NoClassDefFoundError in JSP editor
Attempt to fix so the code is commented for now (related to #67017 and #128360). Later it will be removed if it is OK.