Bug Fix # 128098 NoClassDefFoundError when dropping a web service client onto a J2EE 1.4 page
For the shared J2EE14 project case we need to search for the jaxrpc16 library in the global
library manager - because if the App server associated with the project
already has the classes required for jaxrpc16 support then the jaxrpc16 library refrence
is not added to the project by the web services support module and therefore the library
cannot be found in the library manager associated with the project.