Fix IZ=100185 - creating diagram returns UndeclaredThrowableException & NoClassDefFoundError exceptions. The class PaletteElementNode defined in ModelingPalette is missing in org-netbeans-modules-uml-palette module when building the whole UML suite (not sure what has changed in the build that causes this). Because of the missing class, the uml palette can not be opened when a diagram is opened. Solution: I refactored the code to move the PaletteElementNode class to a separate file. This seems to solve the problem.