Bug# - 217965 - java.lang.NoClassDefFoundError: org/netbeans/modules/glassfish/common/ServerDetails - reverted API changes to keep getInstantiatingIterator() method in ServerUtilities