Bug Fix # 131969 NoClassDefFoundError: javax/ejb/CreateException
Needed to retain the .jar file from the J2EE (App Server) classpath
containing the ejb2.0 classes in the designtime classpath.